---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas}}
  selector: 
    matchLabels: {{ .Values.selectors | toYaml | nindent 6}}
  template:
    metadata: {{ .Values.metadata | toYaml | nindent 6}}
    spec:
      containers:
      - name: {{ .Release.Name }}-con
        image: {{ .Values.containers.image}}:{{ .Values.containers.tag}}
        ports:
        - containerPort: {{ .Values.containers.ports.containerport}}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
         