apiVersion: v1
kind: Pod
metadata:
  name: nonode-name
  labels:
    app: nopractice
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 100Mi