apiVersion: v1
kind: Pod
metadata: 
  name: node-name
  labels:
    app: practice
spec:
  nodeSelector: 
    test: dev
  containers: 
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
      resources: 
        limits:
          cpu: 100m
          memory: 100Mi
