replicas: 4
selectors:  
  app: "nginx"
  version: "1.0"
metadata:
  labels:
    app: "nginx"
    version: "1.0"
containers:
  image: nginx
  tag: "1.27"
  ports: 
    containerport: "80"
resources:
  limits:
    memory: "128Mi"
    cpu: "200m"
  requests: 
    memory: "64Mi"
    cpu: "100m"