apiVersion: v1
kind: Pod
metadata:
  name: test-3
spec:
  containers:
    - name: mysql
      image: mysql:8.0-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: dhille143
        - name: MYSQL_DATABASE
          value: nop
        - name: MYSQL_USER
          value: dhille143
        - name: MYSQL_PASSWORD
          value: dhille143
         