apiVersion: v1
kind: Pod
metadata:
  name: test-1
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: alpine
      image: alpine
      args: 
        - sleep
        - 10s
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 1000m
          memory: 0.5Gi