apiVersion: v1
kind: Pod
metadata: 
  name: test-4
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:jdk17
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          memory: 500m
          cpu: 256mi
        limits:
          memory: 1000m
          cpu: 1Gi
