apiVersion: v1
kind: pod
metadata: 
  name: data-base
  labels:
    app: mysql
spec:
  containers: 
    - name: sql-cnt
      image: mysql:8.0-debian
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: dhille143
        - name: MYSQL_DATABASE
          value: nop
        - name: MYSQL_USER
          value: dhille
        - name: MYSQL_PASSWORD
          value: dhille143
      ports:    
        - containerPort: 3306
