--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-deploy
  labels: 
    app: web-deploy
spec: 
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels: 
      app: web
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: web-pod
      labels:
        app: web
    spec: 
      containers: 
        - name: web-container
          image: ngnix
          ports: 
            - containerPort: 80
          resources: 
            limits: 
              cpu: 100m
              memory: 0.5Gi


--- 
apiVersion: v1
kind: Service
metadata: 
  name: web-svc
  labels: 
    app: web-svc
spec: 
  selector:
    app: web
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 32000

