--- 
apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: jenkins-rc
  labels: 
    app: jenkins-1.0
spec: 
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels:
     app: jenkins
  template:
    metadata: 
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers: 
       - name: jenkins
         image: jenkins/jenkins:2.414.3-jdk17
         ports:
           - containerPort: 8080
         resources: 
           limits: 
             cpu: 100m
             memory: 0.5Gi
--- 
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-svc
  
spec: 
  type: NodePort
  selector:
    app: jenkins
  ports: 
   - port: 8080
     targetPort: 8080
     nodePort: 30001