---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd-rs
    
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels: 
      app: httpd
      version: v1.0
  template:
    metadata:
      name: httpd-con
      labels:
        app: httpd-1
    spec: 
      - containers:
          
          image: httpd
          ports:
            containerPort: 80
            porotocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 0.5Gi