apiVersion: v1
kind: ReplicationController
metadata:
  name: rp-conttroller
  labels:
    app: ngnix
    env: dev
    version: "1.0"
    
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers: 
        - name: nginx
          image: nginx


