apiVersion: v1
kind: Pod
metadata: 
  name: nodeselectors
  labels: 
    app: learning
spec: 
  nodeName: "aks-nodepool1-19760478-vmss000001"
  containers: 
    - name: httpd
      image: httpd:2.4
      ports: 
        - containerPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
