--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
 {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{.Values.replicas}}
  minReadySeconds: {{.Values.minReadySeconds}}
  strategy: {{.Values.strategy | toYaml | nindent 4}}
  selector: 
    matchLables: {{ .Values.selectors | toYaml | nindent 6}}
  template: 
    metadata: {{ .Values.metadata | toYaml | nindent 6}}
    spec:
      containers:
      - name: {{ .Release.Name }}-con
        image: {{.Values.image}}:{{.Values.tag}}
        resources: {{.Values.resources | toYaml | nindent 10}}
        env: {{.Values.env | toYaml | nindent 10}}
        ports: {{.Values.ports | toYaml | nindent 10}}
        livenessProbe: {{.Values.livenessProbe | toYaml | nindent 10}}
        readinessProbe: {{.Values.readinessProbe | toYaml | nindent 10}}