---
apiVersion: v1
kind: Service
metadata: {{.Values.metadata | toYaml | nindent 2}}
spec: {{.Values.spec | toYaml | nindent 2 }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-sts
spec:
  minReadySeconds: {{ .Values.minReadySeconds }}
  replicas: {{ .Values.replicas}}
  selector: 
    matchLables: {{ .Values.selector | toYaml | nindent 6 }}
  serviceName: {{ .Values.metadata.name }}
  template: 
    metadata: {{ .Values.metadata | toYaml | nindent 6}}
    spec:
      containers:
      - name: {{ .Release.Name }}-con
        image: {{ .Values.containers.image}}:{{ .Values.containers.tag }}
        resources: {{ .Values.resources | toYaml | nindent 8 }}
        ports: {{.Values.ports | toYaml | nindent 10 }}
        env: {{ .Values.env | toYaml | nindent 10 }}
        volumeMounts: {{.Values.volumeMounts | toYaml | nindent 10 }}
  volumeClaimTemplates: {{ .Values.volumeClaimTemplates | toYaml | nindent 4}}

