--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: trial-1
  labels: 
    app: pratice
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels: 
      app: alpine
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
     name: trial-rc
     labels: 
       app: alpine
    spec:
      containers:
        - name: alpine-1
          image: alpine
          args: 
            - sleep
            - 1d
          livenessProbe: 
            httpGet:
              path: /
              port: 80
          ports: 
            - containerPort: 80
          resources: 
            limits: 
              cpu: 100m
              memory: 0.5Gi
        - name: httpd-1
          image: httpd
          livenessProbe: 
            httpGet:
              path: /
              port: 80

--- 
apiVersion: v1
kind: Service
metadata: 
  name: web-svc
  labels: 
    app: alpine-svc
spec: 
  selector:
    app: web
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 32500
