---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actvity-1
  labels:
    app: tomcat-1
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: tomcat-rs
      labels: 
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:9-jdk11-corretto
          livenessProbe:
            httpGet:
              port: 80
              path: /
          ports: 
            - containerPort: 8080
          readinessProbe: 
            httpGet:
              port: 80
              path: /
          resources: 
            limits: 
              cpu: 500m
              memory: 250Mi
          
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat-svc
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32500
    
  
    
