--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: css-demo
  annotations:
    kubernetes.io/change-cause: "version v2.0"
spec:
  replicas: 4
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend-app
      version: "v1.0"
  template:
    metadata:
      labels:
        app: frontend-app
        version: "v1.0"
    spec:
      containers:
      - name: dep-con
        image: dhillevajja/dep-dmtest:2.0
        resources:
          requests:
            memory: "24Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: "NodePort"
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32500



