annotations:
  kubernetes.io/change-cause: "version v2.0"
replicas: 4
minReadySeconds: 10
strategy:
  type: RollingUpdate
  rollingUpdate: 
    maxSurge: 25%
    maxUnavailable: 25%
selectors:  
  app: frontend-app
  version: "v1.0"
metadata:
  labels:
    app: frontend-app
    version: "v1.0"
image: dhillevajja/dep-dmtest
tag: "2.0"
resources:
  requests:
    memory: "24Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"
env:
  - name: https_url
    vlaue: www.youtube.com
ports:
  - containerPort: 80
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe: 
  httpGet: 
    path: /
    port: 80
## service file 
metadata: 
  name: myapp-svc
spec:
  type: "NodePort"
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32500
    
 

 