--- 
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: sample1
  labels: 
    app: daemonset
spec: 
  minReadySeconds: 10
  selector: 
    matchLabels: 
      app: httpd1
  template: 
    metadata: 
      labels: 
        app: httpd1
    spec:
      containers: 
        - name: httpd
          image: httpd 


   