apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  # Encode your secrets using base64
  saPassword: {{ .Values.secrets.saPassword | b64enc | quote }}
