apiVersion: apps/v1
kind: Deployment
metadata: 
  name: trial1-depoly
spec:
  minReadySeconds: 30
  replicas: 10
  selector:
    matchLabels: 
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
    type: RollingUpdate
  template:
    metadata:
      name: trail-rs
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: tomcat:jdk17
          resources:
            limits:
              cpu: 200m
              memory: 0.5Gi
          ports: 
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: web-svc
  labels: 
    app: web-svc
spec: 
  selector:
    app: jenkins
  type: NodePort
  ports: 
    - port: 8080
      targetPort: 8080
      nodePort: 32000
